zidoro/pomatez

- package.json
- public/electron.js
- public/sprite.svg
- src/containers/Config/elements/Setting.js
Reverts roldanjrCodeArts9711/productivity-timer#22
> Revert "Version 1.0.0 Pre-Release of the App"

- .gitignore
- app/public/electron.js
This change is to resolve #58 and resolve #49
> Changed hotkeys to bind and unbind on focus

- app/renderer/src/routes/Timer/PriorityCard.tsx
Hide unnecessary text to make interface more clean
> Make timer interface more clean

- app/main/jest.config.js
- app/main/package.json
- app/main/src/helpers/globalShortcuts.ts
- app/main/src/lifecycleEventHandlers/__tests__/fullScreenBreak.test.ts
- app/main/src/lifecycleEventHandlers/fullScreenBreak.ts
- app/main/src/main.ts
- yarn.lock
- As a user, I would like to be able to quit the fullscreen mode during a break.
- This problem is referenced in #136
- Extract the event logic for `SET_FULLSCREEN_BREAK` to a separate handler
- Register shortcuts upon entering full screen (Esc, Cmd+W) and add callback to exit fullscreen
- Unregister shortcuts upon exiting full screen (Esc, Cmd+W)
- Add some rudimentary test (using jest and jest-runner/electrion)
- Can I improve the structure in any way?
- Am I missing an important case ?
> Fix: Enable exit fullscreen break (see #136)

- app/renderer/src/routes/Tasks/TaskCard.tsx
- app/renderer/src/routes/Tasks/TaskFormButton.tsx
- app/renderer/src/routes/Tasks/TaskHeader.tsx
Just a minor change to add the ctrl+enter shortcut to add new tasks quickly.
> Added support to ctrl+enter to add tasks

- .github/workflows/codeql-analysis.yml
Just a little extra to do some code analysis to help find common vulnerabilities.
> chore(ci): add codeql-analysis.yml

- .github/workflows/build.yml
- app/renderer/src/routes/Tasks/TaskCard.tsx
- app/renderer/src/routes/Tasks/TaskFormButton.tsx
This will flag up react warnings and other parts to make sure that the commits are fine.
I've also cleaned up the last warnings stopping it from compiling atm in the ci.
> chore(ci): add test build action

- app/main/package.json
- app/main/src/main.ts
- yarn.lock
Now while running the tools the dev console will pop up as well as the react and redux plugins will be installed on the dev console. This should help debugging inside the actual app rather than having to use the browser.
> chore: improve dev tools for better dev experience

- website/package.json
- website/src/components/Navigation.tsx
- website/src/contexts/NavContext.tsx
- website/src/hooks/useContextProvider.ts
- website/src/styles/components/header.ts
- website/src/styles/sections/download.ts
Fixes a bug where clicking a navigation link would make the scrollbar disappear.
Also fixes horizontal scrolling bug at certain viewport sizes.
> Fix scrolling issues

- release-please-config.json
If this is here the releases will show as a pre-release
> chore(ci): remove pre-release flag

- app/renderer/src/routes/Config/SliderSection.tsx
> tweak: increase max rounds to 10

- app/main/package.json
- app/main/src/main.ts
- yarn.lock
> fix: update to electron 18 and lower uuid version to fix errors on different operating systems

- app/main/package.json
- app/main/src/store/index.ts
- app/renderer/src/styles/components/titlebar.ts
A few small bug fixes for release. The icon not building properly on mac and the logo being draggable as an image rather than a title bar on the main screen.
> fix: small bug fixes

- app/main/src/lifecycleEventHandlers/fullScreenBreak.ts
- app/main/src/main.ts
- app/renderer/public/index.html
this should fix your fullscreen issues @roldanjr
> Fullscreen fix

- app/main/package.json
Seems to fix at least on linux. Will do a quick test on windows too.
> fix: missing app icon

- app/renderer/src/hooks/useTime.ts
- app/renderer/src/routes/Config/SliderSection.tsx
- app/renderer/src/routes/Timer/Counter/Counter.tsx
- app/renderer/src/routes/Timer/Counter/CounterTimer.tsx
- app/renderer/src/styles/routes/timer/counter.ts
* increase maximum focus minutes in config
* refactor: return hours from useTime hook since we need to display hours in our timer
* enhance: display hours on timer screen
---------
> feat: increase maximum focus time to 2 hours (#383)

- .github/workflows/release-please.yml
> ci: Add Homebrew bump-packages action

- app/renderer/src/routes/Config/ConfigSlider.tsx
- app/renderer/src/routes/Config/SliderSection.tsx
Hi, I fixed the #402.
I would like you to pay attention to the comments in the `ConfigSlider.tsx` in [2nd commit.](https://github.com/zidoro/pomatez/commit/c7b1056c63c12d1f302e43f039e70d858c290a93)
That is something we should fix by making another commit but I wanted to include main developers in this.
**Tested on windows portable & installer.**
https://github.com/zidoro/pomatez/assets/45315917/cba50181-61f5-4c50-ba02-1643e09df132
> Fix: Changing time configuration with keyboard did not work - #402

- .github/workflows/release-please.yml
- .pre-commit-config.yaml
- CHANGELOG.md
- app/renderer/package.json
- app/renderer/src/contexts/connectors/TauriConnector.tsx
- app/renderer/src/routes/Config/ConfigSlider.tsx
- app/tauri/Cargo.lock
- app/tauri/Cargo.toml
- app/tauri/release-prep/release-prep.js
- app/tauri/src/main.rs
- app/tauri/tauri.conf.json
- yarn.lock
It should be opening the links in the native browser rather than new windows.
> fix: tauri opening links in new windows

- app/renderer/src/routes/Settings/StickySection.tsx
- app/renderer/src/styles/routes/settings.ts
> feat: add a link to the discord in the app

- .github/workflows/build-tauri.yml
- .github/workflows/build.yml
- .github/workflows/website-deploy.yml
- app/electron/electron-builder/afterSign.js
- app/electron/package.json
- app/tauri/Cargo.lock
- app/tauri/Cargo.toml
- app/tauri/src/main.rs
- app/tauri/tauri.conf.json
- yarn.lock
Enabling the Tauri builds to be signed for apple use
> Mac Signing

- .github/workflows/release-please.yml
- .pre-commit-config.yaml
- package.json
While the action will flag as failed, this configuration at least was able to create a pr, so I've set it to continue on error.
For now I will run these manually when they fail, though will try to update the config as updates come out.
> chore: fork user

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
Just some setup stuff to help with compiling the code from github containers
> chore: updating devcontainer
