- app/public/electron.js
This fixes the keybinds staying when you click x on the application.
It doesn't matter if register and focus are both called as they will silently fail if something is already registered.
> Added registry events for hide and show

- .github/workflows/build.yml
Helps with being able to test in vm's and such without having to compile locally for each.
> chore(ci): upload artifacts

- website/src/components/SVG.tsx
- website/src/hooks/useIsBrowser.ts
Gatsby had an issue rendering the SVG properly at build time which meant the icon wouldn't display properly until it had been toggled. Forcing it to render on the client-side seems like an acceptable workaround.
> Fix theme toggler icon

- app/main/package.json
- release-please-config.json
- yarn.lock
This is a temporary fix to build with the correct version number while I re-configure the npm project. It seems setting the release-type on a lerna project needs a bit more configuration.
> chore(ci): bump version for main package.json & fix release issue

- app/main/src/main.ts
- app/renderer/src/routes/Tasks/TaskDetails/MDPreviewer.tsx
Fixes #257
Links with the _blank target will now automatically open in a new browser as well as markdown target has been set to _blank
> fix: link new window

- app/renderer/src/hooks/useTargetOutside.ts
- app/renderer/src/routes/Tasks/TaskFormButton.tsx
This should fix #258 
Though @roldanjr might want to check if the new behavior is acceptable.
I wanted to make it snap to the bottom only If out of view but that was harder than expected due to the bottom being scrollable and semi transparent it causes it to snap where its not visible
So the result is you can no longer close tasks by clicking off them (checked and its the same as apps like todoist) and it will snap the new card to the center of the div
> fix: data loss

- .github/workflows/release-please.yml
This is to fix the clashing files on release. I have tested it on my own fork and it works fine.
> chore(ci): stop upload of duplicate files [skip ci]

- app/main/src/main.ts
Keyboard shortcuts such as cut, copy, paste etc are currently not working on Mac, but do work when clicking on their respective options via the context menu.
It looks thats because this functionality requires the Mac `Edit` application menu which currently does not exist (See this issue https://github.com/electron/electron/issues/3787).
Created this PR to add the app and edit menu's (App Menu with just `Quit` option is there currently by default).
Only added the menus for Mac because it doesn't look like Linux has this issue (Haven't tried windows yet but guessing its the same) and aside from the edit controls that already exist in the context menu, it wouldn't really be adding anything useful.
Used the `appMenu` role option here so that it creates the default Mac App menu. All the other …
> Set Application Menu  to Fix Mac Shortcuts

- app/renderer/src/hooks/useTime.ts
- app/renderer/src/routes/Config/SliderSection.tsx
- app/renderer/src/routes/Timer/Counter/Counter.tsx
- app/renderer/src/routes/Timer/Counter/CounterTimer.tsx
- app/renderer/src/styles/routes/timer/counter.ts
Increased the maximum focus time on config screen to 120 minutes or 2 hours & then displayed hours on the timer screen along side with minutes and seconds.
This PR fixes [363](https://github.com/zidoro/pomatez/issues/363)
_Tested on windows, installer and portable version._
Please let me know if I did anything wrong.
> #363 - Increase maximum focus time to 2 hours

- app/renderer/src/components/Navigation.tsx
- Disabled dragging of navigation links.
- Tested on windows, installer & portable version.
- This pr fixes [378](https://github.com/zidoro/pomatez/issues/378)
> 378 Disable dragging for navigation links

- app/renderer/src/routes/Timer/Counter/CounterTimer.tsx
- app/renderer/src/styles/routes/timer/control.ts
- app/renderer/src/styles/routes/timer/counter.ts
I have fixed broken layout bug which appeared after we added 120 minutes max config. I did minimum modifications to fix this. @roldanjr 
This PR fixes https://github.com/zidoro/pomatez/issues/389
_Tested on windows, installer and portable version._
Here are some comparisons, broken vs fixed screenshots.
> fix: compact mode layout broke with 120 minutes max timer config

- app/main/package.json
- app/main/src/main.ts
- yarn.lock
Need to test if this works or not. Based on the documentation it seems like whatever installer/auto updater we have may be what is needed here. Though hopefully not.
> fix: toast notification

- CHANGELOG.md
- app/main/package.json
- app/main/src/helpers/analytics.ts
- app/main/src/main.ts
- app/main/src/store.ts
- app/renderer/src/styles/routes/tasks/card.ts
This fixes an issue where the underlying electron store is called and errors are thrown.
The logic should be fine though we need to keep an eye in case this causes other issues.
> Fix #411 Javascript Error

- .github/workflows/release-please.yml
> ci: Add winget-releaser

- app/renderer/src/contexts/connectors/TauriConnector.tsx
On Windows, Tauri throws an error when trying to enable the autostart feature when it is already on.
This PR checks that status to avoid the error
ref https://github.com/tauri-apps/plugins-workspace/issues/24#issuecomment-1528958008
> fix(tauri): check autostart status to prevent error with `@tauri-apps/plugin-autostart` on Windows

- app/tauri/build.rs
- app/tauri/src/commands.rs
- app/tauri/src/global_shortcuts.rs
- app/tauri/src/main.rs
- app/tauri/src/system_tray.rs
- app/tauri/src/updater.rs
- package.json
- yarn.lock
Tested on a Macbook. Need to test on 
Need to test on windows as well as some other dpi displays.
> Fix scaling issues on high dp displays

- app/renderer/src/routes/Tasks/TaskFormButton.tsx
- app/tauri/Cargo.lock
- app/tauri/tauri.conf.json
Also fixed it for Tauri
Should fix or implement most of [#271](https://github.com/zidoro/pomatez/issues/271)
Before it worked on Electron though used old character codes rather than the .code value from the key event.
> feat: shortcuts for adding new cards with `Enter` & `Ctrl+Enter`

- .github/workflows/release-please.yml
- .pre-commit-config.yaml
- package.json
The action itsself was fine though I forgot you need to add secrets: inherit for the secrets to run in underlying actions even on the same repo.
1.6.4 will be what 1.6.3 should have been.
> fix: electron and tauri signing (release 1.6.3 was skipped)

- app/renderer/src/contexts/connectors/ElectronConnector.tsx
The incorrect object was being sent to the backend. This is an error only for the electron version.
I mark it as chore because the bug isn't yet in production
> chore: error message thrown every second

- README.md
- The analytics.ts link is broken in README.md [shield-privacy](https://github.com/zidoro/pomatez#shield-privacy)
> Fix analytics.ts link in README.md

- app/renderer/src/routes/Tasks/TaskList.tsx
- app/renderer/src/styles/routes/tasks/card.ts
- app/renderer/src/styles/routes/tasks/tasks.ts
> :bug: Adds text wrapping for long words in the title

- app/renderer/src/contexts/CounterContext.tsx
I had forgotten to check that the master was building without the warnings as it was building fine locally. These warnings are really irritating that they fully block a release.
> fix: react warning that was blocking the previous release

- .github/workflows/release-please.yml
the maintainer has moved this to require @main to work. This is a bad idea but seems the only way for this to run for now.
> chore: update winget release action
